name: app
description: nx go/flutter playground

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.10
  flutter_test:
    sdk: flutter
  gap: ^2.0.0
  http: ^0.13.4


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

